IM.init({
    "id": 275667666,
    "ts": 1720107313,
    "key": "2b9e04e2064ce7240ef3757d84cb712c1d56b702",
    "url": "im3666",
    "friends": [],
    "editable": 1,
    "emoji": 1,
    "version": 51,
    "unr": "",
    "average_time": false,
    "admins": [],
    "gid": 0,
    "gname": "",
    "ddfriends": false,
    "ddfriends_sel": [],
    "writeHash": "4ce2103ab80bd77ae3",
    "chats": [],
    "chat_photos": [],
    "emails": [],
    "friendsLoaded": 0,
    "photo": "https:\/\/pp.vk.me\/c629430\/v629430666\/27f9b\/AiYUGvlPrGg.jpg",
    "name": "Kate",
    "timeshift": 3600,
    "peer": 326224331,
    "tabs": {
        "326224331": {
            "hash": "a979ed52c6ff3f5340faf8454",
            "photo": "https:\/\/pp.vk.me\/c629328\/v629328331\/34743\/NK0Bjrxdj6E.jpg",
            "name": "Daniela",
            "tab_text": "Daniela&nbsp;Looloo",
            "idisabled": false,
            "msgs": {
                "28785": [0, 0, 0],
                "28786": [1, 0, 0],
                "28787": [1, 0, 0],
                "28788": [0, 0, 0],
                "28789": [0, 0, 0],
                "28790": [1, 0, 0],
                "28791": [1, 0, 0],
                "28792": [0, 0, 0],
                "28793": [1, 0, 0],
                "28794": [1, 0, 0],
                "28795": [0, 0, 0],
                "28796": [0, 0, 0],
                "28797": [1, 0, 0],
                "28798": [0, 0, 0],
                "28799": [1, 0, 0],
                "28800": [0, 0, 0],
                "28801": [1, 0, 0],
                "28802": [0, 0, 0],
                "28803": [0, 0, 0],
                "28804": [1, 0, 0],
                "28805": [0, 0, 0],
                "28806": [0, 0, 0],
                "28807": [0, 0, 0],
                "28808": [1, 0, 0],
                "28809": [0, 0, 0],
                "28810": [0, 0, 0],
                "28811": [0, 0, 0],
                "28812": [1, 0, 0],
                "28813": [0, 0, 0],
                "28814": [1, 0, 0]
            },
            "all_shown": 0,
            "href": "\/id326224331",
            "sex": "1",
            "block": [],
            "folders": null,
            "q_offset": 0,
            "inUpto": 28813,
            "outUpto": 28814
        }
    },
    "mutedPeers": [],
    "tab_template": "<div class=\"im_tab %muted%\" id=\"im_tab%peer_id%\"><div class=\"im_tab1\"><div class=\"im_tab2\">\n  <table cellspacing=\"0\" cellpadding=\"0\"><tr>\n    <td><div class=\"im_tab3\"><span class=\"im_tab4\">%peer_name%<\/span><span id=\"im_unread%peer_id%\"><\/span><\/div><\/td>\n    <td><div class=\"im_tab_muted_span\"><\/div><\/td>\n    <td><div class=\"im_tabx\" onclick=\"cancelEvent(event); IM.closeTab(%peer_id%);\"><\/div><\/td>\n  <\/tr><\/table>\n<\/div><\/div><\/div>",
    "author_link": "\/katemicha",
    "real_author_link": "\/katemicha",
    "txt_template": "<div class=\"im_txt_wrap im_editable_txt \" data-peer=\"%peer_id%\" id=\"im_txt_wrap%peer_id%\" style=\"display: none;\">\n  <div class=\"im_title_wrap\" id=\"im_title_wrap%peer_id%\">\n    <input type=\"text\" class=\"text im_title\" id=\"im_title%peer_id%\" maxlength=\"64\" \/>\n  <\/div>\n  <div class=\"im_editable\" tabindex=\"0\" contenteditable=\"true\" id=\"im_editable%peer_id%\" placeholder=\"Введите Ваше сообщение..\"><\/div>\n  <div class=\"im_txt_warn\" id=\"im_txt_warn%peer_id%\"><\/div>\n<\/div>",
    "drow_template": "<div class=\"dialogs_row %row_class%  dialogs_msg%msg_id% %is_important%\" data-important=\"%is_important_val%\" id=\"im_dialog%peer%\" onmouseover=\"addClass(this, 'dialogs_row_over');\" onmouseout=\"removeClass(this, 'dialogs_row_over');\" onclick=\"IM.addPeer(%peer%); return false;\" data-date=\"%timestamp%\" data-unread=\"%unread_cnt%\">\n  <div class=\"dialogs_star_wrap %is_star%\">\n    <div class=\"dialogs_star _dialogs_star\" onclick=\"IM.starDialogD(this, %peer%); event.cancelBubble = true;\" onmouseover=\"IM.starTT(this, event)\"><\/div>\n  <\/div>\n  <div class=\"dialogs_del_wrap\">\n    <div class=\"dialogs_del\" onclick=\"IM.deleteDialog(%peer%, ''); event.cancelBubble = true;\" onmouseover=\"showTooltip(this, {text: 'Удалить диалог', black: 1, shift: [14, 4, 0]});\"><\/div>\n  <\/div>\n  <table cellpadding=\"0\" cellspacing=\"0\" class=\"dialogs_row_t\">\n    <tr>\n      <td class=\"dialogs_photo\">\n        %photo%\n      <\/td>\n      <td class=\"dialogs_info\">\n        <div class=\"dialogs_user wrapped\">%user_link%<\/div>\n        %online%\n        <div class=\"dialogs_date\">%date%<\/div>\n      <\/td>\n      <td class=\"dialogs_msg_contents\">\n        <div class=\"dialogs_msg_body %body_class% clear_fix\">\n          %inline_author%\n          <div class=\"dialogs_msg_text wrapped fl_l\">%body%<\/div>\n        <\/div>\n      <\/td>\n      <td class=\"dialogs_unread_td\">\n        <div class=\"dialogs_unread %unread_class%\" id=\"dialogs_unread%peer%\">%unread%<\/div>\n      <\/td>\n    <\/tr>\n  <\/table>\n<\/div>",
    "time_system": false,
    "left_menu": 0,
    "mark_hash": "1454141845_afa2323bf81c715a1b",
    "share_timehash": "1454141845_5abb2f88689114ebc5",
    "multi_peers_max": 50,
    "attachments_num_max": 10,
    "ctrl_submit_hint": "<div class=\"im_submit_tail_wrap\"><div class=\"im_submit_tail\"><\/div><\/div>\n<div class=\"im_submit_hint_wrap\">\n  <div class=\"im_submit_hint_title\">Настройки отправки<\/div>\n  <div id=\"im_submit_hint_opts\">\n    <div class=\"radiobtn on\" onclick=\"radiobtn(this, 0, 'im_submit'); IM.onSubmitSettingsChanged(0);\"><div><\/div><b>Enter<\/b> — отправка сообщения<br><b>Shift+Enter<\/b> — перенос строки<\/div>\n    <div class=\"radiobtn \" onclick=\"radiobtn(this, 1, 'im_submit'); IM.onSubmitSettingsChanged(1);\"><div><\/div><b>Ctrl+Enter<\/b> — отправка сообщения<br><b>Enter<\/b> — перенос строки<\/div>\n  <\/div>\n<\/div>",
    "ctrl_submit": false,
    "susp_msg": "<div class=\"im_msg_susp_wrap\" id=\"im_susp_wrap%msg_id%\">\n  <div class=\"im_msg_susp_title\">\n    Это подозрительное сообщение.\n    <a href=\"\" onclick=\"return IM.checkSpamSingle(%msg_id%);\">Показать текст<\/a>.\n  <\/div>\n  <div class=\"im_msg_susp\">%message%<\/div>\n<\/div>",
    "searchOffset": false,
    "searchQ": "",
    "importantOffset": false,
    "spamOffset": false,
    "spamFlushhash": "542572f9bbac32599b",
    "spam": {"hash": "46aa48cfa86338246f"},
    "lastSearchQ": "",
    "searchTip": "Сообщения до определенной даты",
    "timestamp": 1454141845,
    "transport_frame": "https:\/\/imv4.vk.com\/im_frame.php#309",
    "upload_options": {
        "url": "https:\/\/pu.vk.com\/c630128\/upload.php",
        "params": {
            "act": "do_add",
            "aid": -3,
            "gid": 0,
            "mid": 275667666,
            "hash": "f9b08b794f5faf3ac74aa7d48f49253c",
            "rhash": "831a00d562b4bb693f6356aa957f31aa",
            "vk": 1,
            "from_host": "vk.com"
        },
        "opts": {
            "server": "630128",
            "default_error": 1,
            "error_hash": "98ceccccf685cbe7c13d6d884697ee64",
            "ext_re": "\\.(gif|jpg|jpeg|png)$",
            "lang": {"max_files_warning": "Вы можете прикрепить к сообщению не более 10 файлов."}
        }
    },
    "notify_msg": 1,
    "gfilter": null,
    "im_doc_hash": "",
    "nu": 1,
    "emoji_stickers": [[-1, 1], [1, 1, 2], [3, 1, 2], [85, 0, 2], [84, 0, 2]],
    "mute_enabled": true,
    "dialogs_members": {
        "326224331": {"first_name": "Daniela", "last_name": "Looloo", "sex": "1"},
        "21456230": {"first_name": "Василий", "last_name": "Воронин", "sex": "2"},
        "295442752": {"first_name": "Агнет", "last_name": "Соболева", "sex": "1"},
        "148246060": {"first_name": "Адель", "last_name": "Самара", "sex": "1"},
        "40681108": {"first_name": "Семён", "last_name": "Шендрик", "sex": "2"}
    }
});
;(function () {
    var cb = function () {
        Notifier.init({
            "queue_id": "events_queue275667666",
            "timestamp": 1767579134,
            "key": "qVd579EaMEaU3_QmNmMDspluTApBZKoXSht0UW4SrWpPW0BRR8QFArTx1ws7M_5b",
            "uid": 275667666,
            "version": 10,
            "debug": false,
            "instance_id": "NDkyNjQx",
            "server_url": "https:\/\/queuev4.vk.com\/im666",
            "frame_path": "https:\/\/queuev4.vk.com\/q_frame.php?7",
            "frame_url": "im666",
            "refresh_url": "https:\/\/vk.com\/notifier.php",
            "fc": {
                "version": 23,
                "state": {
                    "clist": {"min": true, "x": false, "y": false},
                    "tabs": {
                        "295442752_": {"min": false, "fx": true},
                        "21456230_": {"min": false, "fx": true},
                        "148246060_": {
                            "min": false,
                            "x": 0.831844,
                            "y": -1.000000,
                            "w": 0.132422,
                            "h": 0.321757,
                            "fx": 1
                        },
                        "326224331_": {"min": false, "fx": 1}
                    },
                    "version": 23
                },
                "state_hash": "1454141845_63eb908fa92cc29697"
            }
        })
    }
    if (window.vk && window.vk.loaded) cb(); else addEvent(window, 'DOMContentLoaded load', cb);
})();